# DCBS Evaluation Configuration with DBSCAN Clustering
# Verified settings from debugging session

# Model configuration  
model_path: "meta-llama/Llama-3.2-1B-Instruct"

# DCBS clustering configuration
clustering:
  method: "dbscan"              # CRITICAL: Use DBSCAN clustering
  dbscan_eps: 0.3               # DBSCAN epsilon parameter
  dbscan_min_samples: 2         # DBSCAN minimum samples

# Main DCBS parameters
clusters: 8                     # Number of clusters for K-means (fallback)
top_n: 50                       # Number of top tokens to consider
k: 8                            # Cluster parameter

# Sampling parameters
p_values: [0.9]                 # For top-p sampling

# Paths
benchmark: "data/arc_easy_full.json"
output_file: "results/dcbs_evaluation.csv"

# DCBS algorithm parameters
dcbs_params:
  temperature: 1.0              # Temperature for token sampling
  min_tokens_for_clustering: 3  # Minimum token count for clustering
  clustering_random_seed: 42    # Random seed for clustering
  min_batch_size: 3584          # Batch size for processing

# Debug configuration
debug_mode: false
enable_cluster_history: true    # ENABLE cluster history for evaluation

# Cache configuration (ENABLED)
cache:
  embedding_cache_size: 1000    # Maximum cached token embeddings
  cluster_cache_size: 200       # Maximum cached clustering results

# Chain-of-thought reasoning (ENABLED by default)
include_cot: true               # Enable chain-of-thought reasoning

# Logging configuration
log_level: "INFO"
log_file: "results/dcbs_eval.log"

# Memory management
memory:
  report_threshold_mb: 10
  gc_threshold_mb: 1000
  include_details: true
  warning_threshold_mb: 2000
  critical_threshold_mb: 3500
  batch_size: 5

# Error handling
error_handling:
  max_retries: 3
  continue_on_error: true 